import type { Metadata } from "next";
import { CodeBlock } from "@run402/ui";
import { DocHeader, RefTable, Section } from "@/components/doc";
import { Callout } from "@/components/callout";

export const metadata: Metadata = { title: "Configuration" };

const c = (t: string) => <code className="font-mono">{t}</code>;

export default function ConfigDocs() {
  return (
    <div>
      <DocHeader
        title="Configuration"
        lead="A typed run402.config.ts and a handful of environment variables."
      />

      <Section title="run402.config.ts">
        <p>
          Generated by <code className="font-mono">run402 init</code>. Typed with{" "}
          <code className="font-mono">defineConfig</code> for full autocomplete.
        </p>
        <CodeBlock
          code={`import { defineConfig } from "run402"

export default defineConfig({
  projectKey: process.env.RUN402_SECRET_KEY ?? "",
  environment: "sandbox",
  framework: "express",
  port: 4000,
  baseUrl: "http://localhost:3001",
})`}
          lang="ts"
          filename="run402.config.ts"
        />
      </Section>

      <Section title="Fields">
        <RefTable
          head={["Field", "Default", "Description"]}
          rows={[
            [c("projectKey"), "—", "Secret key (sk_…). Prefer an env var."],
            [c("environment"), c('"sandbox"'), '"live" arrives with Stripe.'],
            [c("framework"), c('"express"'), "express | next | fastify"],
            [c("port"), c("4000"), "Local dev port your app listens on."],
            [c("baseUrl"), "localhost:3001", "Run402 control-plane origin."],
          ]}
        />
      </Section>

      <Section title="Environment variables">
        <RefTable
          head={["Variable", "Used by", "Description"]}
          rows={[
            [c("RUN402_SECRET_KEY"), "SDK, CLI", "Project secret key (sk_…)."],
            [c("RUN402_BASE_URL"), "SDK, CLI", "Control-plane origin override."],
          ]}
        />
      </Section>

      <Callout type="warning" title="Never commit secrets">
        <code className="font-mono">run402 init</code> writes an env-backed config — your
        secret key is read from the environment, not hardcoded into the file.
      </Callout>
    </div>
  );
}
